<?php
// This file is part of UCLA Modify Coursemenu plugin for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * The course menu moodleform - acts as a proxy to a custom UI.
 *
 * @package    block_ucla_modify_coursemenu
 * @copyright  2014 UC Regents
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

require_once($CFG->dirroot . '/lib/formslib.php');
/**
 * The course menu form is an instance of moodleform, but we use a custom UI.
 *
 * @copyright  2014 UC Regents
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class ucla_modify_coursemenu_form extends moodleform {
    /**
     *  This is going to serve as a proxy for our custom UI.
     */
    public function definition() {
        $mform =& $this->_form;

        $courseid  = $this->_customdata['courseid'];
        $section = $this->_customdata['section'];
        $landingpage = $this->_customdata['landing_page'];
        $daterangejson = $this->_customdata['daterangejson'];
        $hideautogeneratedcontentdefault = $this->_customdata['hide_autogenerated_content'];
        // Remember enablelandingpagebydates setting.
        $enablelandingpagebydatesdefault = $this->_customdata['enable_landingpage_by_dates'];

        $mform->addElement('hidden', 'courseid', $courseid);
        $mform->setType('courseid', PARAM_INT);

        $mform->addElement('hidden', 'section', $section);
        $mform->setType('section', PARAM_INT);

        $mform->addElement('hidden', 'newsections', '',
            array('id' => block_ucla_modify_coursemenu::NEWNODES_DOMNODE));
        $mform->setType('newsections', PARAM_TEXT);

        $mform->addElement('hidden', 'sectionsorder', '',
            array(
                'id' => block_ucla_modify_coursemenu::SECTIONSORDER_DOMNODE
            ));
        $mform->setType('sectionsorder', PARAM_TEXT);

        $mform->addElement('hidden', 'landingpage', $landingpage,
            array(
                'id' => block_ucla_modify_coursemenu::LANDINGPAGE_DOMNODE
            ));
        $mform->setType('landingpage', PARAM_TEXT);

        $mform->addElement('hidden', 'serialized', '',
            array(
                'id' => block_ucla_modify_coursemenu::SERIALIZED_DOMNODE
            ));
        $mform->setType('serialized', PARAM_TEXT);

        // "Landing Page by Dates" form element for passing data back and forth between front-end and back-end.
        $mform->addElement('hidden', 'daterange', $daterangejson,
            array(
                'id' => block_ucla_modify_coursemenu::DATERANGE_DOMNODE
            ));
        $mform->setType('daterange', PARAM_TEXT);

        $mform->addElement('html', html_writer::tag('div',
                get_string('javascriptrequired', 'group'),
                array('id' => block_ucla_modify_coursemenu::PRIMARY_DOMNODE)));

        $mform->addElement('button', 'addsectionbutton',
                get_string('addnewsection', 'block_ucla_modify_coursemenu'),
                array('id' => block_ucla_modify_coursemenu::ADD_SECTION_BUTTON));

        $mform->addElement('header', 'additional_options', get_string('additional_options',
                'block_ucla_modify_coursemenu'));

        $mform->addElement('advcheckbox', 'hideautogeneratedcontent', '',
                get_string('hideautogeneratedcontent', 'block_ucla_modify_coursemenu'));
        $mform->setDefault('hideautogeneratedcontent', $hideautogeneratedcontentdefault);

        // Place actual enablelandingpagebydates checkbox.
        $mform->addElement('advcheckbox', 'enablelandingpagebydates', '',
                get_string('enablelandingpagebydates', 'block_ucla_modify_coursemenu'));
        $mform->setDefault('enablelandingpagebydates', $enablelandingpagebydatesdefault);

        $this->add_action_buttons();
    }
}
