<?php
// This file is part of UCLA Modify Coursemenu plugin for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings for UCLA Modify Coursemenu plugin.
 *
 * @package    block_ucla_modify_coursemenu
 * @copyright  2014 UC Regents
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Modify sections';

$string['addnewsection'] = 'Add new section';
$string['deletingcontents'] = 'Delete content';

$string['additional_options'] = 'Additional options';
$string['hideautogeneratedcontent'] = 'Do not display auto-generated links';

// Javascript strings.
$string['new_sectnum'] = 'New';
$stirng['default_new_section'] = 'New section';
$string['section'] = 'Section';
$string['title'] = 'Title';
$string['hide'] = 'Hide';
$string['delete'] = 'Delete';
$string['landing_page'] = 'Landing page';

$string['newsection'] = 'New section';
$string['couldnotdeletesection'] = 'The section "{$a->name}" could not be deleted because it is not empty. Please empty the section before deleting it.';
$string['deletesectioncontents'] = 'At least one of the section(s) you are deleting have content. Please check that these are the changes you wish to make.';
$string['tbdel'] = 'To delete:';
$string['deleteconfirm'] = 'Delete content';

$string['successmodify'] = 'Your change has been applied.';
$string['failuremodify'] = 'There was an error writing records to the database. Your modifications were not saved.';
$string['modifymore'] = 'Modify more sections';

// Modify course menu event log handler.
$string['coursemenu_modified'] = 'Modified site menu';

// SSC-1205 - Landing Page by Dates.
$string['landing_page_by_dates'] = 'Landing page by Dates';
$string['landingpagebydatesto'] = 'to';
$string['landingpagebydatesempty'] = 'You must select a start date.';
$string['landingpagebydatesequivalent'] = 'Duplicate start dates.';
$string['landingpagebydatesstartoverlap'] = 'Start date overlaps another range.';
$string['landingpagebydatessequential'] = 'Date range is not sequential.';
$string['landingpagebydatesrangeoverlap'] = 'Date range overlaps with another range.';
$string['enablelandingpagebydates'] = 'Enable landing page by dates.';

// Cache string for "Landing Page by Dates".
$string['cachedef_landingpagebydatesdb'] = 'Cache to store revision times of Landing Page by Dates database data.';
$string['cachedef_landingpagebydatesdisplay'] = 'Cache to store revision times of Landing Page by Dates display data.';

// Admin panel strings.
$string['modifysections'] = 'Modify sections';
