@ucla @local_publicprivate
Feature: Autogenerated forums private by default
    As an instructor
    I want auto generated forums to be private by default
    So that content is not visible to unenrolled users

    Background: UCLA environment and srs site exists
        Given I am in a ucla environment
        And A ucla srs site exists

    Scenario: Viewing SRS site as an instructor
        And I log in as instructor
        And I go to a ucla srs site
        Then I should see "Announcements Forum(Private Course Material)"
        And I should see "Discussion forum(Private Course Material)"


    @javascript @test
    Scenario: Deleting and adding Announcement and Discussion forums
        And I log in as instructor
        And I go to a ucla srs site
        And I turn editing mode on
        And I delete "Announcements" activity
        And I delete "Discussion forum" activity
        And I reload the page
        Then I should see "Announcements Forum(Private Course Material)"
        And I should see "Discussion forum(Private Course Material)"
        