@ucla @local_publicprivate @core_edit @CCLE-3101
Feature: Autogenerated forums private by default
    As an instructor
    I want auto generated forums to be private by default
    So that content is not visible to unenrolled users

   Background: UCLA environment and srs site exists
      Given I am in a ucla environment
      And the following "users" exist:
         | username | firstname | lastname | email |
         | teacher1 | Teacher | 1 | teacher1@asd.com |
      And the following ucla "sites" exist:
         | fullname | shortname | type |
         | Course 1 | C1 | srs |
      And the following ucla "enrollments" exist:
         | user | course | role |
         | teacher1 | C1 | editingteacher |

   Scenario: Default forums should be private
      Given I log in as "teacher1"
      When I follow "Course 1"
      Then "Announcements" activity should be private
      And "Discussion forum" activity should be private

   @javascript @totest
   Scenario: Deleting the Announcement and Discussion forums
      Given I log in as "teacher1"
      When I follow "Course 1"
      When I turn editing mode on
      And I open "Announcements" actions menu
      And I delete "Announcements" activity
      And I open "Discussion forum" actions menu
      And I delete "Discussion forum" activity
      And I reload the page
      Then "Announcements" activity should be private
      And "Discussion forum" activity should be private
        