@ucla @local_publicprivate
Feature: Autogenerated forums private by default
    As an instructor
    I want auto generated forums to be private by default
    So that content is not visible to unenrolled users

    Background: UCLA environment and srs site exists
        Given I am in a ucla environment
        And the following "users" exists:
          | username | firstname | lastname | email |
          | teacher1 | Teacher | 1 | teacher1@asd.com |
        And the following ucla "sites" exists:
            | fullname | shortname | type |
            | course 1 | C1 | srs |
        And the following ucla "enrollments" exists:
          | user | course | role |
          | teacher1 | C1 | editingteacher |

    Scenario: Viewing SRS site as an instructor
        And I log in as ucla "teacher1"
        And I browse to site "C1"
        Then "Announcements Forum" activity should be private
        And "Discussion forum" activity should be private

#    @javascript
    Scenario: Deleting the Announcement and Discussion forums
        And I log in as ucla "teacher1"
        And I browse to site "C1"
        And I turn editing mode on
        And I delete "Announcements" activity
        And I delete "Discussion forum" activity
        And I reload the page
        Then "Announcements Forum" activity should be private
        And "Discussion forum" activity should be private
        