<?php
// This file is part of the UCLA shared theme for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Reorder and modify the navigation.
 *
 * @package   theme_uclashared
 * @copyright 2018 UC Regents
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace theme_uclashared;
defined('MOODLE_INTERNAL') || die();

/**
 * Adds/remove/rearranges nodes in navigation drawer.
 *
 * Borrows a lot of code from: https://moodle.org/plugins/local_boostnavigation.
 *
 * @package   theme_uclashared
 * @copyright 2018 UC Regents
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class modify_navigation {

    /**
     * Holds sections that should have js to collapse/expand.
     *
     * @var array
     */
    private $collapsenodesforjs = array();

    /**
     * Course node to add elements at the end.
     *
     * @var navigation_node
     */
    private $_coursenode = null;

    /**
     * Stores course format object.
     *
     * @var format_base 
     */
    private $format = null;

    /**
     * Moodle's navigation tree.
     *
     * @var navigation_node
     */
    private $navigation = null;

    /**
     * Flag to track whether divider is displayed after course sections.
     *
     * @var boolean
     */
    private $showdividercalled = false;

    /**
     * Magic getter.
     *
     * @param string $name
     * @return mixed
     */
    public function __get($name) {
        global $COURSE;
        if ($name == 'coursenode') {
            if (!isset($this->_coursenode)) {
                $this->_coursenode = $this->navigation->find($COURSE->id, \navigation_node::TYPE_COURSE);
                if (empty($this->_coursenode)) {
                    // Course must be hidden and user does not have access.
                    // Create fake node.
                    $this->_coursenode = \navigation_node::create('coursenode');
                }
            }
            return $this->_coursenode;
        }
    }

    /**
     * Adds the auto-generated Activities/Resources section.
     */
    private function add_activityresources() {
        global $CFG, $COURSE;

        // See if we should show Activities/Resources section.
        $formatoptions = $this->format->get_format_options();
        if (!empty($formatoptions['hide_autogenerated_content'])) {
            return;
        }

        // See if there are any modules.
        $modnamesplural = get_module_types_names(true);
        $modnamesused = get_fast_modinfo($COURSE->id)->get_used_module_names();

        // We don't bother displaying labels because they don't have an index.
        if (isset($modnamesused['label'])) {
            unset($modnamesused['label']);
        }

        if (empty($modnamesused)) {
            return;
        }

        // Create activities/resources course node. Flat node so it.
        $activitiesnode = \navigation_node::create(get_string('activitiesresources', 'theme_uclashared'),
                new \moodle_url('/course/view.php', array('id' => $COURSE->id)), // We have to add a URL to the course node,
                                                                                // otherwise the node wouldn't be added to
                                                                                // the flat navigation by Boost.
                                                                                // There is no better choice than the course
                                                                                // home page.
                \navigation_node::TYPE_CUSTOM,
                null,
                'themeuclasharedactivities',
                null);
        // Prevent that the activities course node is marked as active and added to the breadcrumb when showing the
        // course home page.
        $activitiesnode->make_inactive();
        $activitiesnode->isexpandable = true;

        // Get the user preference for the collapse state of the activities node and set the collapse and hidden
        // node attributes of the activity nodes accordingly. At the same time, reallocate the parent of the
        // existing section nodes.
        $userprefactivitiesnode = get_user_preferences('theme_uclashared-collapse_'.
                'themeuclasharedactivitiesnode', 0);
        if ($userprefactivitiesnode == 1) {
            $activitiesnode->collapse = true;
        } else {
            $activitiesnode->collapse = false;
        }

        // Add the activities node to the end of the course navigation.
        // If activities node is to be displayed as a new flat nav block
        if ($this->showdividercalled === false) {
            $activitiesnode = new \flat_navigation_node($activitiesnode, 0);
            $activitiesnode->set_showdivider(true);
            $this->showdividercalled = true;
        }
        $activitiesnode = $this->coursenode->add_node($activitiesnode);

        // Create an activity course node for each activity type.
        foreach ($modnamesused as $mod => $name) {
            $modpath = '/mod/' . $mod . '/index.php';
            if (file_exists($CFG->dirroot . $modpath)) {

                $modnode = \navigation_node::create($modnamesplural[$mod],
                        new \moodle_url('/mod/'.$mod.'/index.php', array('id' => $COURSE->id)),
                        \navigation_node::TYPE_ACTIVITY,
                        null,
                        'themeuclasharedactivity'.$mod,
                        new \pix_icon('icon', '', $mod));

                if ($userprefactivitiesnode == 1) {
                    $modnode->hidden = true;
                } else {
                    $modnode->hidden = false;
                }

                // Add the activity course node to the coursehome node.
                $this->coursenode->add_node($modnode);

                // Need to set parent only after adding it.
                $modnode->set_parent($activitiesnode);
            }
        }

        // Make activities collapsible.
        $this->collapsenodesforjs[] = 'themeuclasharedactivities';
    }

    /**
     * Add link to media resources.
     */
    private function add_mediaresources() {
        global $COURSE;

        $params['course'] = $COURSE;

        $mediaresourcenode = block_method_result('ucla_media', 'get_navigation_nodes', $params);
        if (!empty($mediaresourcenode)) {
            // If media resources node is to be displayed as a new flat nav block.
            if ($this->showdividercalled === false) {
                $mediaresourcenode = new \flat_navigation_node($mediaresourcenode, 0);
                $mediaresourcenode->set_showdivider(true);
                $this->showdividercalled = true;
            }
            $this->coursenode->add_node($mediaresourcenode);
        }
    }

    /**
     * Add link to Library reserves.
     */
    private function add_libraryreserves() {
        global $COURSE;

        $params['course'] = $COURSE;

        $libraryreserves = block_method_result('ucla_library_reserves', 'get_navigation_nodes', $params);
        if (!empty($libraryreserves)) {
            // Iterate the array if multiple library reserves are to be displayed.
            foreach ($libraryreserves as $libraryreservenode) {
                // If library reserve node is to be displayed as a new flat nav block.
                if ($this->showdividercalled === false) {
                    $libraryreservenode = new \flat_navigation_node($libraryreservenode, 0);
                    $libraryreservenode->set_showdivider(true);
                    $this->showdividercalled = true;
                }
                $this->coursenode->add_node($libraryreservenode);
            }
        }
    }

    /**
     * Add More section.
     */
    private function add_more() {
        global $COURSE;

        // Create More Section node. Flat node so it.
        $morenode = \navigation_node::create(get_string('moresection', 'theme_uclashared'),
                new \moodle_url('/course/view.php', array('id' => $COURSE->id)), // We have to add a URL to the course node,
                                                                                // otherwise the node wouldn't be added to
                                                                                // the flat navigation by Boost.
                                                                                // There is no better choice than the course
                                                                                // home page.
                \navigation_node::TYPE_CUSTOM,
                null,
                'themeuclasharedmore',
                null);
        // Prevent that the more section node is marked as active and added to the breadcrumb when showing the
        // course home page.
        $morenode->make_inactive();
        $morenode->isexpandable = true;

        // Get the user preference for the collapse state of the more section node and set the collapse and hidden
        // node attributes of the more section node accordingly. At the same time, reallocate the parent of the
        // existing section nodes.
        $userprefmorenode = get_user_preferences('theme_uclashared-collapse_'.
                'themeuclasharedmorenode', 1);
        if ($userprefmorenode == 1) {
            $morenode->collapse = true;
        } else {
            $morenode->collapse = false;
        }

        // If More Section node is to be displayed as a new flat nav block.
        if ($this->showdividercalled === false) {
            $morenode = new \flat_navigation_node($morenode, 0);
            $morenode->set_showdivider(true);
            $this->showdividercalled = true;
        }

        // Add the more section node.
        $this->coursenode->add_node($morenode);

        // $params is used as a parameter to send to the blocks which generate the nav nodes
        $params['course'] = $COURSE;

        // Add library reserve guide node.
        $librarynode = block_method_result('ucla_library_portal', 'get_navigation_nodes', $params);
        if (!empty($librarynode)) {
            if ($userprefmorenode == 1) {
                $librarynode->hidden = true;
            } else {
                $librarynode->hidden = false;
            }

            // Add the library node to the coursehome node.
            $this->coursenode->add_node($librarynode);

            // Need to set parent only after adding it.
            $librarynode->set_parent($morenode);
        }

        // Add subject area nodes.
        $subjectlinks = block_method_result('ucla_subject_links', 'get_navigation_nodes', $params);
        if (!empty($subjectlinks)) {
            // Iterate the array if multiple subject links are to be displayed
            foreach ($subjectlinks as $subjectlinknode) {
                if ($userprefmorenode == 1) {
                    $subjectlinknode->hidden = true;
                } else {
                    $subjectlinknode->hidden = false;
                }

                // Add the library node to the coursehome node.
                $this->coursenode->add_node($subjectlinknode);

                // Need to set parent only after adding it.
                $subjectlinknode->set_parent($morenode);
            }
        }

        // Add MyEngineering node.
        $myengineeringnode = block_method_result('ucla_myengineer', 'get_navigation_nodes', $params);
        if (!empty($myengineeringnode)) {
            if ($userprefmorenode == 1) {
                $myengineeringnode->hidden = true;
            } else {
                $myengineeringnode->hidden = false;
            }

            // Add the library node to the coursehome node.
            $this->coursenode->add_node($myengineeringnode);

            // Need to set parent only after adding it.
            $myengineeringnode->set_parent($morenode);
        }

        // Make more section collapsible.
        $this->collapsenodesforjs[] = 'themeuclasharedmore';

        if (empty($librarynode) && empty($subjectlinks) && empty($myengineeringnode)) {
            $morenode->remove();
        }
    }

    /**
     * There are certain nodes that do not highlight in the lefthand nav, either
     * because of core bugs, or our messing around with the navigation API, or
     * because the URL in the node do not match the actual URL users end up on.
     * 
     * See ticket CCLE-7646.
     */
    public function higlight_nodes() {
        global $DB, $PAGE;

        $url = $PAGE->url;

        if ($url->compare(new \moodle_url('/course/view.php'), URL_MATCH_BASE)) {            
            // Setting a landing page does not highlight a section, because the
            // section is not in the URL, so need to find and highlight it 
            // ourselves.
            $section = $this->format->figure_section();
            
            // Site info does not get highlighted, because Moodle highlights the
            // course node on section 0.
            if (empty($url->get_param('section')) || $section === 0) {
                // Show all is a special node.
                if ($section === $this->format::UCLA_FORMAT_DISPLAY_ALL) {
                    $nodeid = 'showall';
                } else {
                    $nodeid = $DB->get_field('course_sections', 'id',
                        array('course' => $PAGE->course->id, 'section' => $section));
                }
                $node = $this->navigation->find($nodeid, \navigation_node::TYPE_SECTION);
            }
        } else if (substr($url->out_as_local_url(), 0, 7) === '/grade/') {
            // If we are viewing any grade report, highlight grades node.
            $node = $this->navigation->find('grades', \navigation_node::TYPE_SETTING);
        }

        if (!empty($node)) {
            $node->make_active();
        }
    }

    /**
     * Check if the page is editable and the user has editing permissions.
     * 
     * @return boolean If button is to be displayed return true, otherwise false.
     */
    public function is_editing_button_displayed() {
        global $PAGE;
        // Currently checks if the page is grader page, course section page or 
        // syllabus section page.
        return (($PAGE->url->compare(new \moodle_url('/grade/report/grader/index.php'), URL_MATCH_BASE)) ||
                ($PAGE->user_allowed_editing() &&
                ($PAGE->url->compare(new \moodle_url('/course/view.php'), URL_MATCH_BASE) ||
                $PAGE->url->compare(new \moodle_url('/local/ucla_syllabus/index.php'), URL_MATCH_BASE))));
    }

    /**
     * Add link to Admin panel page, see CCLE-7193.
     */
    private function add_adminpanel() {
        global $PAGE;

        $section = $this->format->figure_section();
        $sectiontype = 'section';
        $sectionvalue = $section;

        if ($section == UCLA_FORMAT_DISPLAY_ALL) {
            $sectiontype = 'show_all';
            $sectionvalue = 1;
        }

        $params = array('courseid' => $PAGE->course->id,
                $sectiontype => $sectionvalue);

        if (has_capability('format/ucla:viewadminpanel', $PAGE->context)) {
            $adminurl = new \moodle_url('/course/format/ucla/admin_panel.php', $params);
            $courseadmin = \navigation_node::create(get_string('adminpanel', 'format_ucla'),
                        $adminurl, \navigation_node::TYPE_SETTING,
                        null, 'courseadministration', new \pix_icon('i/settings', ''));

            // If editing button is not displayed, courseadmin becomes a new tree parent
            if (!$this->is_editing_button_displayed()) {
                $courseadmin = new \flat_navigation_node($courseadmin, 0);
                $courseadmin->set_showdivider(true);
            }
            $this->coursenode->add_node($courseadmin);
        }
    }

    /**
     * Add Un/Enrol me button to navigation drawer.
     */
    private function add_enrolme() {
        global $COURSE;

        if (is_role_switched($COURSE->id)) {
            return;
        }
        // add enrol nodes
        enrol_add_course_navigation($this->coursenode, $COURSE);
        // If editing button and courseadmin are not displayed, un/enrolment becomes a new tree parent.
        if (!($this->coursenode->find('editingmode', \navigation_node::TYPE_SETTING)) &&
                !($this->coursenode->find('courseadministration', \navigation_node::TYPE_SETTING))) {
            // Try fetching Enrol me button.
            $enrolnode = $this->coursenode->find('enrolself', \navigation_node::TYPE_SETTING);
            // Try fetching Unenrol me button if Enrol me does not exist.
            if (!$enrolnode) {
                $enrolnode = $this->coursenode->find('unenrolself', \navigation_node::TYPE_SETTING);
            }
            // Create flatnav only if self enrol button is displayed.
            if ($enrolnode) {
                $enrolnode->remove();
                $enrolnode = new \flat_navigation_node($enrolnode, 0);
                $enrolnode->set_showdivider(true);
                $this->coursenode->add_node($enrolnode);
            }
        }
    }

    /**
     * Add Turn editing on/off.
     */
    private function add_editingmode() {
        global $PAGE, $USER;

        // Exit function if not on an editable page or if does not have permission to edit
        if (!$this->is_editing_button_displayed()) {
            return;
        }

        // If on grader page, editing button should mirror for grader
        if ($PAGE->url->compare(new \moodle_url('/grade/report/grader/index.php'), URL_MATCH_BASE)) {
            // Code below is copied from /grade/report/grader/index.php
            // Lines 32, 67-68, 93-109

            $page = optional_param('page', 0, PARAM_INT);   // active page
            // return tracking object
            $gpr = new \grade_plugin_return(array('type'=>'report', 'plugin'=>'grader', 'courseid'=>$PAGE->course->id, 'page'=>$page));

            // page params for the turn editing on
            $options = $gpr->get_options();
            $options['sesskey'] = sesskey();

            if ($USER->gradeediting[$PAGE->course->id]) {
                $options['edit'] = 0;
                $editingmode = true;
            } else {
                $options['edit'] = 1;
                $editingmode = false;
            }
            $editurl = new \moodle_url('index.php', $options);

        } else {
            // If user can edit the page
            if ($PAGE->user_allowed_editing()) {
                // Add the turn on/off settings.
                if ($PAGE->url->compare(new \moodle_url('/course/view.php'), URL_MATCH_BASE)) {
                    // We are on the course page, retain the current page params e.g. section.
                    $baseurl = clone($PAGE->url);
                    $baseurl->param('sesskey', sesskey());
                } else {
                    // Edit on the main course page.
                    $baseurl = new \moodle_url('/course/view.php',
                            array('id' => $PAGE->course->id,
                                  'return' => $PAGE->url->out_as_local_url(false),
                                  'sesskey' => sesskey()));
                }

                $editurl = clone($baseurl);
                if ($PAGE->user_is_editing()) {
                    $editurl->param('edit', 'off');
                    $editingmode = true;
                } else {
                    $editurl->param('edit', 'on');
                    $editingmode = false;
                }
            }
        }

        // Set button label and icon depending on editing mode
        if ($editingmode === true) {
            $editstring = get_string('turneditingoff');
            $editicon = 'e/tick';
        } else {
            $editstring = get_string('turneditingon');
            $editicon = 'i/edit';
        }

        // Create flat nav node so we can set divider.
        $turneditingon = new \flat_navigation_node(\navigation_node::create($editstring, $editurl,
                \navigation_node::TYPE_SETTING,
                null, 'editingmode', new \pix_icon($editicon, '')), 0);
        $turneditingon->set_showdivider(true);
        $this->coursenode->add_node($turneditingon);
    }

    /**
     * Add Show all node if using UCLA format.
     */
    private function add_show_all() {
        global $PAGE;

        $showallurl = new \moodle_url('/course/view.php',
                array('id' => $PAGE->course->id, 'show_all' => 1));
        $showall = \navigation_node::create(get_string('show_all', 'format_ucla'),
                    $showallurl, \navigation_node::TYPE_SECTION,
                    null, 'showall', null);

        $this->coursenode->add_node($showall);
    }
    
    /**
     * Add 'Add Section' node if using UCLA format.
     */
    private function add_new_section() {
        global $PAGE;

        // See if we should show "Add Section" option.
        if (!$PAGE->user_is_editing()) {
            return;
        }

        $straddsections = get_string('addsections', 'theme_uclashared');
        $url = new \moodle_url('/course/changenumsections.php',
                array('courseid' => $PAGE->course->id, 'insertsection' => 0, 'sesskey' => sesskey(), 'sectionreturn' => 1));
        $icon = new \pix_icon('t/add', $straddsections);

        $addsections = \navigation_node::create($straddsections,
                    $url, \navigation_node::TYPE_SECTION,
                    null, 'addsection', $icon);

        $addsections->addsectionclass = 'add-sections';
        $addsections->dataaddsections = $straddsections;
        $this->coursenode->add_node($addsections);
    }

    /**
     * Adds link to UCLA syllabus if on a course type that supports it.
     */
    private function add_syllabus() {
        global $CFG;
        // Add node for syllabus (if needed).
        include_once($CFG->dirroot . '/local/ucla_syllabus/locallib.php');
        if (class_exists('ucla_syllabus_manager')) {
            global $COURSE;
            $uclasyllabusmanager = new \ucla_syllabus_manager($COURSE);
            $syllabusnode = $uclasyllabusmanager->get_navigation_nodes();
            if (!empty($syllabusnode)) {
                // Found node, so add to course before first section.               
                $siteinfonode = null;
                $children = $this->coursenode->get_children_key_list();
                // Find 1st child that is an integer.
                foreach ($children as $child) {
                    if (intval($child) !== 0) {
                        $siteinfonode = $child;
                        break;
                    }
                }
                $this->coursenode->add_node($syllabusnode, $siteinfonode);
            }
        }
    }

    /**
     * Add link to parent page if TA site.
     */
    private function add_tasiteparent() {
        global $PAGE;
        // Add node parent class home.
        $tasiteenrol = block_method_result('ucla_tasites', 'get_tasite_enrol_meta_instance', $PAGE->course->id);
        if (!empty($tasiteenrol)) {
            $tasiteparentnode = \navigation_node::create(get_string('returntocourse', 'block_ucla_tasites'),
                                new \moodle_url('/course/view.php', array(
                                    'id' => $tasiteenrol->customint1
                                )),
                                \navigation_node::TYPE_SECTION, null, 'parentsitehome', null);
            $siteinfonode = null;
            $children = $this->coursenode->get_children_key_list();
            // Find 1st child that is an integer.
            foreach ($children as $child) {
                if (intval($child) !== 0) {
                    $siteinfonode = $child;
                    break;
                }
            }
            $this->coursenode->add_node($tasiteparentnode, $siteinfonode);
        }
    }

    /**
     * Changes or removes icons for certain nodes.
     */
    private function change_icons() {
        global $PAGE;

        $nodestochange['participants']['type'] = \navigation_node::TYPE_CONTAINER;
        $nodestochange['participants']['icon'] = new \pix_icon('i/users', get_string('participants'));
        foreach ($nodestochange as $name => $nodeinfo) {
            if ($node = $this->navigation->find($name, $nodeinfo['type'])) {
                $node->icon = $nodeinfo['icon'];
            }
        }

        // The settingsnav is not set if we are purging caches.
        @$settingsnav = $PAGE->settingsnav; // Supress NOTICE when purging caches.
        if (empty($settingsnav)) {
            return;
        }

        // Add gear icon to Site administration. Treat separately since it is
        // harder to find.
        // Code from lib/navigationlib.php:flat_navigation->initialise().
        $admin = $settingsnav->find('siteadministration', \navigation_node::TYPE_SITE_ADMIN);
        if (!$admin) {
            // Try again - crazy nav tree!
            $admin = $settingsnav->find('root', \navigation_node::TYPE_SITE_ADMIN);
        }
        if ($admin) {
            $admin->icon = new \pix_icon('t/preferences', get_string('administrationsite'));
        }
    }

    /**
     * Rearrange nodes.
     */
    private function rearrange_nodes() {
        global $PAGE;
        
        $nodestomove = array('grades' => \navigation_node::TYPE_SETTING,
            'coursedownload' => \navigation_node::TYPE_SECTION,
            'participants' => \navigation_node::TYPE_CONTAINER);
        foreach ($nodestomove as $name => $type) {
            if ($node = $this->navigation->find($name, $type)) {
                $node->remove();
                
                // If Admin panel is not displayed, then need to set Grades to
                // have a divider.
                if ($name === 'grades' &&
                        !has_capability('format/ucla:viewadminpanel', $PAGE->context)) {
                    $node = new \flat_navigation_node($node, 0);
                    $node->set_showdivider(true);             
                }
                
                $this->coursenode->add_node($node);
            }
        }
    }

    /**
     * Remove items we do not want.
     */
    private function remove_nodes() {
        $nodestoremove = array('badgesview' => \navigation_node::TYPE_SETTING,
            'competencies' => \navigation_node::TYPE_SETTING,
            'home' => \navigation_node::TYPE_ROOTNODE,
            'privatefiles' => \navigation_node::TYPE_SETTING,
            'calendar' => \navigation_node::TYPE_CUSTOM);

        foreach ($nodestoremove as $name => $type) {
            if ($node = $this->navigation->find($name, $type)) {
                $node->remove();
            }
        }

        // Next, we will need the mycourses node and the mycourses node children in any case and don't want to fetch them more
        // than once.
        $mycoursesnode = $this->navigation->find('mycourses', \navigation_node::TYPE_ROOTNODE);
        $mycourseschildrennodeskeys = $mycoursesnode->get_children_key_list();

        if ($mycoursesnode) {
            // Hide mycourses node.
            $mycoursesnode->showinflatnavigation = false;

            // Hide all courses below the mycourses node.
            foreach ($mycourseschildrennodeskeys as $k) {
                $mycoursesnode->get($k)->showinflatnavigation = false;
            }
        }
    }

    /**
     * Change link location for the grades node if set in course settings.
     */
    private function redirectgradelink() {
        global $PAGE;

        $formatoptions = $this->format->get_format_options();
        if (empty($formatoptions['myuclagradelinkredirect'])) {
            return;
        }
        $gradelinknode = $this->navigation->find('grades', \navigation_node::TYPE_SETTING);
        if ($gradelinknode && $formatoptions['myuclagradelinkredirect']) {
            $gradelinknode->action = new \moodle_url('https://be.my.ucla.edu');
        }
    }

    /**
     * Show the roles that a user can switch to.
     */
    private function add_changerole() {
        global $PAGE;

        $courseid = $PAGE->course->id;
        $returnurl = $PAGE->url->out_as_local_url(false);
        $sessionkey = sesskey();

        // If role is already switched, display "Return to normal role".
        if (is_role_switched($courseid)) {
            $rolereturnurl = new \moodle_url('/course/switchrole.php', array(
                'id' => $courseid,
                'sesskey' => $sessionkey,
                'switchrole' => 0,
                'returnurl' => $returnurl
            ));

            $rolereturn = \navigation_node::create(get_string('switchrolereturn'),
                        $rolereturnurl, \navigation_node::TYPE_SETTING,
                        null, 'themeuclasharedswitchrole', new \pix_icon('a/logout', 'normalrole'));
            $this->coursenode->add_node($rolereturn);
        } else {
            // Otherwise display blocks to switch to available roles.
            $pagecontext = \context_course::instance($courseid);
            $roles = get_switchable_roles($pagecontext);
            // Check if there are any roles user can switch to.
            if (is_array($roles) && (count($roles) > 0)) {
                // Create main dropdown node "Switch role to".
                $switchrolenode = \navigation_node::create(get_string('switchroleto'),
                        new \moodle_url('/course/view.php', array('id' => $courseid)), // We have to add a URL to the course node,
                                                                                // otherwise the node wouldn't be added to
                                                                                // the flat navigation by Boost.
                                                                                // There is no better choice than the course
                                                                                // home page.
                        \navigation_node::TYPE_CUSTOM,
                        null,
                        'themeuclasharedswitchrole',
                        new \pix_icon('i/switchrole', 'switchrole'));
                // Prevent that the switch role node is marked as active and added to the breadcrumb when showing the
                // course home page.
                $switchrolenode->make_inactive();
                $switchrolenode->isexpandable = true;

                // Get the user preference for the collapse state of the switch role node and set the collapse and hidden
                // node attributes of the more section node accordingly. At the same time, reallocate the parent of the
                // existing section nodes.
                $userprefswitchrolenode = get_user_preferences('theme_uclashared-collapse_'.
                        'themeuclasharedswitchrole', 1);
                if ($userprefswitchrolenode == 1) {
                    $switchrolenode->collapse = true;
                } else {
                    $switchrolenode->collapse = false;
                }

                // Add the switch role node to the coursehome node.
                $this->coursenode->add_node($switchrolenode);

                // For each role, create new node and add it to "Switch role" node.
                foreach ($roles as $key => $role) {
                    $roleurl = new \moodle_url('/course/switchrole.php', array(
                        'id' => $courseid,
                        'switchrole' => $key,
                        'sesskey' => $sessionkey,
                        'returnurl' => $returnurl
                    ));
                    $rolenode = \navigation_node::create($role,
                            $roleurl,
                            \navigation_node::TYPE_ACTIVITY,
                            null,
                            $key,
                            new \pix_icon('spacer', ''));

                    if ($userprefswitchrolenode == 1) {
                        $rolenode->hidden = true;
                    } else {
                        $rolenode->hidden = false;
                    }

                    // Add the role node to the coursehome node.
                    $this->coursenode->add_node($rolenode);

                    // Need to set parent only after adding it.
                    $rolenode->set_parent($switchrolenode);
                  }

                // Make switch role node collapsible.
                $this->collapsenodesforjs[] = 'themeuclasharedswitchrole';
            }
        }
    }

    /**
     * Apply custom CSS class selectors to course sections if TA site.
     */
    private function tasite_theme() {
        // Check if TA site, indirectly by checking for TA parent site backlink.
        $tasitenode = $this->coursenode->find('parentsitehome' ,\navigation_node::TYPE_SECTION);
        if ($tasitenode) {
            $children = $this->coursenode->get_children_key_list();
            // For each node above and including the showall node, set the tasite parameter.
            foreach ($children as $child) {
                $this->coursenode->find($child ,\navigation_node::TYPE_SECTION)->tasite = 'tasite';
                if ($child == 'showall') {
                    break;
                }
            }
        }
    }

    /**
     * Add Download Course Material link if student.
     */
    private function add_download_course_material() {
        global $CFG, $COURSE;

        // Check if this is a student that can download the archive.
        $coursecontext = \context_course::instance($COURSE->id);
        $isinstructor = has_capability('moodle/course:manageactivities', $coursecontext);
        $canrequest = has_capability('block/ucla_course_download:requestzip', $coursecontext);
        require_once($CFG->dirroot . '/blocks/ucla_course_download/locallib.php');

        if ($isinstructor || !$canrequest || !student_zip_requestable($COURSE)) {
            return;
        }

        // Create the node and add to navigation drawer.
        $coursedownloadnode = \navigation_node::create(get_string('coursedownload', 'block_ucla_course_download'),
                    new \moodle_url('/blocks/ucla_course_download/view.php', array('courseid' => $COURSE->id)),
                    \navigation_node::TYPE_SECTION,
                    null, 'coursedownload', new \pix_icon('t/download', ''));

        $this->coursenode->add_node($coursedownloadnode);
    }
    
    /**
     * Adds text for empty sections and text and color for hidden sections.
     */
    private function add_empty_hidden_text() {
        global $COURSE, $PAGE;
        $sections = get_fast_modinfo($COURSE)->get_section_info_all();
        $emptysectionIDs = array();
        $hiddensectionIDs = array();
        $viewcapability = has_capability('moodle/course:viewhiddensections', $PAGE->context);
        
        foreach ($sections as $section) {
            if (empty($section->sequence) && empty($section->summary)) {
                $emptysectionIDs[$section->id] = null;
            }
            if (!$section->visible) {
                $hiddensectionIDs[$section->id] = null;
            }
        }
        
        $emptysectiontext = get_string('emptysectiontext', 'theme_uclashared');
        $hiddensectiontext = get_string('hiddensectiontext', 'theme_uclashared');
        
        $nodes = $this->navigation->find_all_of_type(\navigation_node::TYPE_SECTION);
        foreach ($nodes as $node) {
            if (array_key_exists($node->key, $emptysectionIDs)) {
                if ($viewcapability) {
                    $node->text .= $emptysectiontext;
                } else {
                    $node->remove();
                    continue;
                }
            }
            if (array_key_exists($node->key, $hiddensectionIDs)) {
                $node->text .= $hiddensectiontext;
                $node->add_class('hidden-node');
            }
        }
    }

    /**
     * Modifies Moodle navigation tree.
     *
     * Called from local/ucla/lib.php: local_ucla_extend_navigation().
     *
     * @param \navigation_node $navigation
     */
    public function run(\navigation_node $navigation) {
        global $PAGE;

        $this->navigation = $navigation;

        // Only make changes for site level or courses with UCLA format.
        if ($PAGE->course->id != SITEID) {
            $this->format = course_get_format($PAGE->course->id);
            if ($this->format->get_format() !== 'ucla') {
                return;
            }
        }

        // Remove nodes.
        $this->remove_nodes();

        // Run course specific changes.
        if ($PAGE->course->id != SITEID) {
            // Add nodes if on course.
            $this->add_syllabus();
            $this->add_tasiteparent();
            $this->add_show_all();
            $this->add_new_section();
            $this->add_libraryreserves();
            $this->add_mediaresources();
            $this->add_activityresources();
            $this->add_more();
            $this->add_editingmode();
            $this->add_adminpanel();
            $this->add_download_course_material();
            $this->add_changerole();
            $this->add_enrolme();

            // Rearrange items.
            $this->rearrange_nodes();

            // Color the nodes if TA site.
            $this->tasite_theme();

            // Redirect grade link to MyUCLA if configured.
            $this->redirectgradelink();

            // Highlight nodes.
            $this->higlight_nodes();
            
            // Modifies display for empty or hidden sections.
            $this->add_empty_hidden_text();
        }

        // Change icons for nodes.
        $this->change_icons();

        // If at least one section needs to be collapsed.
        if (!empty($this->collapsenodesforjs)) {
            // Add JavaScript for collapsing nodes to the page.
            $PAGE->requires->js_call_amd('theme_uclashared/collapsenavdrawernodes', 'init', [$this->collapsenodesforjs]);
            // Allow updating the necessary user preferences via Ajax.
            foreach ($this->collapsenodesforjs as $node) {
                user_preference_allow_ajax_update('theme_uclashared-collapse_'.$node.'node', PARAM_BOOL);
            }
        }
    }
}
