<?php
// This file is part of the UCLA local plugin for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/*
 * Event handlers for the block_ucla_myengineer plugin.
 *
 * @package    block_ucla_myengineer
 * @copyright  2014 UC Regents
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

/**
 * When the course creator has finished, check if it is an Engineering course. 
 * If so, check "Do not display auto-generated links" for upon build and add the
 * "Recent activity" and "Upcoming events" blocks upon build and place them
 * above the "Administration" block.
 * 
 * Responds to the course_creator_finished event.
 * 
 * @param array $edata
 * @return boolean
 */
function set_engineering_default($edata) {
    $page = new moodle_page();
    foreach ($edata->completed_requests as $request) {
        // Only work on hostcourses.
        if (empty($request->hostcourse)) {
            continue;
        }

        // Only work on engineering courses.
        if (!is_engineering($request->courseid)) {
            continue;
        }

        // Check "Do not display auto-generated links" upon build.
        course_get_format($request->courseid)->update_course_format_options(
                array('hide_autogenerated_content' => true));

        // Add the "Recent activity" and "Upcoming events" blocks upon build and
        // place them above the "Administration" block.
        $coursecontext = context_course::instance($request->courseid);
        $page->set_context($coursecontext);
        $page->blocks->add_regions(array(BLOCK_POS_RIGHT), false);
        $page->blocks->add_block('recent_activity', BLOCK_POS_RIGHT, -10, 0, 'course-view-*');
        $page->blocks->add_block('calendar_upcoming', BLOCK_POS_RIGHT, -9, 0, 'course-view-*');
    }
    return true;
}
