@ucla @local_publicprivate @format_ucla @core_edit @CCLE-3101 @CCLE-4649
Feature: Autogenerated forums
    As an instructor
    I want private forums to be auto-generated but deletable for non-srs courses
    So that content is both customizable and not visible to unenrolled users

    Background: UCLA environment and srs/non-srs sites exist
      Given I am in a ucla environment
      And the following "users" exist:
         | username | firstname | lastname | email |
         | teacher1 | Teacher | 1 | teacher1@asd.com |
      And the following ucla "sites" exist:
         | fullname | shortname | type |
         | Course 1 | C1 | srs |
         | Course 2 | C2 | test |
      And the following ucla "enrollments" exist:
         | user | course | role |
         | teacher1 | C1 | editingteacher |
         | teacher1 | C2 | editingteacher |

    Scenario: Default forums should be private
      Given I log in as "teacher1"
      When I follow "Course 1"
      Then "Announcements" activity should be private
      And "Discussion forum" activity should be private
      When I browse to site "C2"
      Then "Announcements" activity should be private
      And "Discussion forum" activity should be private

    Scenario: Deleting the Announcement and Discussion forums
      Given I log in as "teacher1"
      When I follow "Course 1"
      And I turn editing mode on
      And I delete "Announcements" activity
      And I delete "Discussion forum" activity
      Then "Announcements" activity should be private
      And "Discussion forum" activity should be private
      When I browse to site "C2"
      And I delete "Announcements" activity
      And I delete "Discussion forum" activity
      Then I should not see "Announcements"
      And I should not see "Discussion forum"

    @javascript
    Scenario: Deleting an auto-gen forum results in a specific dialog message
      Given I log in as "teacher1"
      When I follow "Course 1"
      And I turn editing mode on
      And I open "Announcements" actions menu
      And I click on "Delete" "link" in the "Announcements" activity
      Then I should see "Are you absolutely sure you want to completely delete the Forum \"Announcements\" and all the data it contains?" in the "Confirm" "dialogue"